name: personal

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-20.04

    env:
      # Change These If You Are Forking The Repo
      GitHubMail: "manofuranium@gmail.com"
      GitHubName: "ElytrA8"

    steps:

    # Either use ngrok method or tmate method
    - name: Start SSH via ngrok
      continue-on-error: true
      timeout-minutes: 340
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        NGROK_REGION: us
        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        # Send connection info to Telegram (optional)
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Self Looping
      run: |
        git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
        cd loop || exit 1
        echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
        git add looper.txt
        git commit -m "Looping at $(date -u +%D-%T%P)"
        git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
