name: personal

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
    inputs:
      name:
        description: You github name
        required: true
      em:
        description: You github email
        required: true
      ng:
        description: You NGROK TOKEN
        required: true
      gh:
        description: You github token
        required: true
      ssh:
        description: Define a pass for ssh
        required: true
      bot:
        description: Token of the Telegram Bot
        required: true
      id:
        description: ID of the grup with bot is member
        required: true

jobs:
  ssh:
    runs-on: ubuntu-20.04

    env:
      # Change These If You Are Forking The Repo
      GitHubName: ${{ github.event.inputs.name }}
      GitHubMail: ${{ github.event.inputs.em }}

    steps:
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email ${GitHubMail}
        git config --global user.name ${GitHubName}
        git config --global color.ui true
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ github.event.inputs.gh }}@github.com" > ~/.git-credentials
        echo "${{ github.event.inputs.gh }}" | docker login docker.pkg.github.com -u ${GitHubName} --password-stdin

    # Either use ngrok method or tmate method
    - name: Start SSH via ngrok
      continue-on-error: true
      timeout-minutes: 340
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ github.event.inputs.ng }}
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        NGROK_REGION: in
        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ github.event.inputs.ssh }}
        # Send connection info to Telegram (optional)
        TELEGRAM_BOT_TOKEN: ${{ github.event.inputs.bot }}
        TELEGRAM_CHAT_ID: ${{ github.event.inputs.id }}

    - name: Self Looping
      run: |
        curl -X POST --header "Authorization: token ${{ github.event.inputs.gh }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/personal.yml/dispatches -d '{"ref":"main"}'
